// <auto-generated />
using System;
using CozinhaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CozinhaAPI.Migrations
{
    [DbContext(typeof(DbAcess))]
    [Migration("20220121134813_tabelasCeI")]
    partial class tabelasCeI
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("CozinhaAPI.Model.Cozinha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("HoraDeAbertura")
                        .HasColumnType("int");

                    b.Property<int>("HoraDeFechamento")
                        .HasColumnType("int");

                    b.Property<string>("NomeDaCozinha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PratoPrincipal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NomeDaCozinha")
                        .IsUnique();

                    b.ToTable("Cozinha");
                });

            modelBuilder.Entity("CozinhaAPI.Model.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CozinhaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDeValidade")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CozinhaId");

                    b.ToTable("Ingrediente");
                });

            modelBuilder.Entity("CozinhaAPI.Model.Ingrediente", b =>
                {
                    b.HasOne("CozinhaAPI.Model.Cozinha", null)
                        .WithMany("Ingrediente")
                        .HasForeignKey("CozinhaId");
                });

            modelBuilder.Entity("CozinhaAPI.Model.Cozinha", b =>
                {
                    b.Navigation("Ingrediente");
                });
#pragma warning restore 612, 618
        }
    }
}
